common: &common
  adapter: postgresql
  username: geoff
  password: mass2742 # from psql setup, see Postgresql

development:
  adapter: postgresql
  username: geoff
  database: martha_develop

test: &test
  <<: *common
  database: myapp_test

production:
  <<: *common
  database: martha_prod


cucumber:
  <<: *test

