common: &common
  adapter: postgresql
  username: geoff
  password: mass2742 # from psql setup, see Postgresql

development:
  <<: *common
  database: martha_prod

test:
  <<: *common
  database: myapp_test

production:
  <<: *common
  database: martha_prod

